# Generated by Django 4.2.9 on 2026-06-23 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('anio', models.IntegerField()),
                ('num_motor', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('num_chasis', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('num_disco', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En mantenimiento'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('km_manual', models.IntegerField(default=0)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Activo',
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_cond', models.CharField(max_length=150)),
                ('apell_cond', models.CharField(max_length=150)),
                ('cedula_cond', models.CharField(max_length=20, unique=True)),
                ('tipolicen_cond', models.CharField(max_length=3)),
                ('telfno_cond', models.CharField(blank=True, max_length=10, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Conductor',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_intervalo', models.IntegerField()),
            ],
            options={
                'db_table': 'ConfiguracionMantenimiento',
            },
        ),
        migrations.CreateModel(
            name='DetalleMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Mantenimiento.configuracionmantenimiento')),
            ],
            options={
                'db_table': 'DetalleMantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('aplica_a', models.CharField(choices=[('cabezal', 'Cabezal'), ('furgon', 'Furgón'), ('plataforma', 'Plataforma'), ('ambos', 'Todos')], max_length=10)),
                ('tipo_control', models.CharField(choices=[('km', 'Por kilometraje'), ('libre', 'Libre')], max_length=5)),
            ],
            options={
                'db_table': 'TipoTrabajo',
            },
        ),
        migrations.CreateModel(
            name='Remolque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('furgon', 'Furgón'), ('plataforma', 'Plataforma')], max_length=10)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En mantenimiento'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Mantenimiento.marca')),
            ],
            options={
                'db_table': 'Remolque',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=15)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('km_odometro', models.IntegerField(blank=True, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mantenimiento.activo')),
                ('cabezal_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_como_ref', to='Mantenimiento.activo')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mantenimiento.conductor')),
                ('remolque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mantenimiento.remolque')),
            ],
            options={
                'db_table': 'Mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='KmManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('km_odometro', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mantenimiento.activo')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'KmManual',
            },
        ),
        migrations.CreateModel(
            name='InsumoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=250)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mantenimiento.detallemantenimiento')),
            ],
            options={
                'db_table': 'InsumoDetalle',
            },
        ),
        migrations.AddField(
            model_name='detallemantenimiento',
            name='mantenimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mantenimiento.mantenimiento'),
        ),
        migrations.AddField(
            model_name='detallemantenimiento',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mantenimiento.tipotrabajo'),
        ),
        migrations.AddField(
            model_name='configuracionmantenimiento',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mantenimiento.marca'),
        ),
        migrations.AddField(
            model_name='configuracionmantenimiento',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mantenimiento.tipotrabajo'),
        ),
        migrations.CreateModel(
            name='CargaCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('km_odometro', models.IntegerField()),
                ('litros', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mantenimiento.activo')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CargaCombustible',
            },
        ),
        migrations.AddField(
            model_name='activo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mantenimiento.marca'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracionmantenimiento',
            unique_together={('marca', 'trabajo')},
        ),
    ]
