# Generated by Django 4.2.9 on 2026-07-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargacombustible',
            name='km_odometro',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='kmmanual',
            name='km_odometro',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
