# Generated by Django 4.2.9 on 2026-06-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaW', '0003_codigorecuperacion_alter_conductor_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('conductor', 'Conductor')], default='conductor', max_length=20),
        ),
    ]
