# Generated by Django 4.2.9 on 2026-06-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaW', '0004_alter_usuario_email_alter_usuario_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitacoraAcciones',
        ),
        migrations.DeleteModel(
            name='Conductor',
        ),
        migrations.DeleteModel(
            name='ConfiguracionMantenimiento',
        ),
        migrations.DeleteModel(
            name='DetalleManTrailer',
        ),
        migrations.DeleteModel(
            name='InsumoDetalleTrailer',
        ),
        migrations.DeleteModel(
            name='MantenimientoTrailer',
        ),
        migrations.DeleteModel(
            name='MarcaTrailer',
        ),
        migrations.DeleteModel(
            name='Trailer',
        ),
    ]
